// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxvGEvAAmb8QB_N-uxhWGwY4pF81d5yHo',
    appId: '1:745527816686:web:992c230799e90b63995eff',
    messagingSenderId: '745527816686',
    projectId: 'finobird-4f4ad',
    authDomain: 'finobird-4f4ad.firebaseapp.com',
    storageBucket: 'finobird-4f4ad.appspot.com',
    measurementId: 'G-MGQMXE3ZR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXWyt0b8yplTr_IfjLTVINHVh-EQQ-4KI',
    appId: '1:745527816686:android:e8a7cf5708893ca6995eff',
    messagingSenderId: '745527816686',
    projectId: 'finobird-4f4ad',
    storageBucket: 'finobird-4f4ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXJVakrbnzH7xEoEuS6aV4gbsREbm-rXI',
    appId: '1:745527816686:ios:ed00170bc2408132995eff',
    messagingSenderId: '745527816686',
    projectId: 'finobird-4f4ad',
    storageBucket: 'finobird-4f4ad.appspot.com',
    iosClientId: '745527816686-5v1k3ahv9jf2c9ic5b7sre24g2u0ngj2.apps.googleusercontent.com',
    iosBundleId: 'com.finobird.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXJVakrbnzH7xEoEuS6aV4gbsREbm-rXI',
    appId: '1:745527816686:ios:ed00170bc2408132995eff',
    messagingSenderId: '745527816686',
    projectId: 'finobird-4f4ad',
    storageBucket: 'finobird-4f4ad.appspot.com',
    iosClientId: '745527816686-5v1k3ahv9jf2c9ic5b7sre24g2u0ngj2.apps.googleusercontent.com',
    iosBundleId: 'com.finobird.app',
  );
}
